// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: options/gorm.proto

/*
Package gorm is a generated protocol buffer package.

It is generated from these files:
	options/gorm.proto

It has these top-level messages:
	GormFileOptions
	GormMessageOptions
	ExtraField
	GormFieldOptions
	GormTag
	HasOneOptions
	BelongsToOptions
	HasManyOptions
	ManyToManyOptions
	AutoServerOptions
	MethodOptions
*/
package gorm

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GormFileOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GormFileOptions) Reset()                    { *m = GormFileOptions{} }
func (m *GormFileOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFileOptions) ProtoMessage()               {}
func (*GormFileOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{0} }

type GormMessageOptions struct {
	Ormable          *bool         `protobuf:"varint,1,req,name=ormable" json:"ormable,omitempty"`
	Include          []*ExtraField `protobuf:"bytes,2,rep,name=include" json:"include,omitempty"`
	Table            *string       `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	MultiAccount     *bool         `protobuf:"varint,4,opt,name=multi_account,json=multiAccount" json:"multi_account,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GormMessageOptions) Reset()                    { *m = GormMessageOptions{} }
func (m *GormMessageOptions) String() string            { return proto.CompactTextString(m) }
func (*GormMessageOptions) ProtoMessage()               {}
func (*GormMessageOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{1} }

func (m *GormMessageOptions) GetOrmable() bool {
	if m != nil && m.Ormable != nil {
		return *m.Ormable
	}
	return false
}

func (m *GormMessageOptions) GetInclude() []*ExtraField {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *GormMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GormMessageOptions) GetMultiAccount() bool {
	if m != nil && m.MultiAccount != nil {
		return *m.MultiAccount
	}
	return false
}

type ExtraField struct {
	Type             *string  `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Tag              *GormTag `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ExtraField) Reset()                    { *m = ExtraField{} }
func (m *ExtraField) String() string            { return proto.CompactTextString(m) }
func (*ExtraField) ProtoMessage()               {}
func (*ExtraField) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{2} }

func (m *ExtraField) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ExtraField) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ExtraField) GetTag() *GormTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GormFieldOptions struct {
	Tag  *GormTag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Drop *bool    `protobuf:"varint,2,opt,name=drop" json:"drop,omitempty"`
	// Types that are valid to be assigned to Association:
	//	*GormFieldOptions_HasOne
	//	*GormFieldOptions_BelongsTo
	//	*GormFieldOptions_HasMany
	//	*GormFieldOptions_ManyToMany
	Association      isGormFieldOptions_Association `protobuf_oneof:"association"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *GormFieldOptions) Reset()                    { *m = GormFieldOptions{} }
func (m *GormFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFieldOptions) ProtoMessage()               {}
func (*GormFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{3} }

type isGormFieldOptions_Association interface {
	isGormFieldOptions_Association()
}

type GormFieldOptions_HasOne struct {
	HasOne *HasOneOptions `protobuf:"bytes,3,opt,name=has_one,json=hasOne,oneof"`
}
type GormFieldOptions_BelongsTo struct {
	BelongsTo *BelongsToOptions `protobuf:"bytes,4,opt,name=belongs_to,json=belongsTo,oneof"`
}
type GormFieldOptions_HasMany struct {
	HasMany *HasManyOptions `protobuf:"bytes,5,opt,name=has_many,json=hasMany,oneof"`
}
type GormFieldOptions_ManyToMany struct {
	ManyToMany *ManyToManyOptions `protobuf:"bytes,6,opt,name=many_to_many,json=manyToMany,oneof"`
}

func (*GormFieldOptions_HasOne) isGormFieldOptions_Association()     {}
func (*GormFieldOptions_BelongsTo) isGormFieldOptions_Association()  {}
func (*GormFieldOptions_HasMany) isGormFieldOptions_Association()    {}
func (*GormFieldOptions_ManyToMany) isGormFieldOptions_Association() {}

func (m *GormFieldOptions) GetAssociation() isGormFieldOptions_Association {
	if m != nil {
		return m.Association
	}
	return nil
}

func (m *GormFieldOptions) GetTag() *GormTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *GormFieldOptions) GetDrop() bool {
	if m != nil && m.Drop != nil {
		return *m.Drop
	}
	return false
}

func (m *GormFieldOptions) GetHasOne() *HasOneOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_HasOne); ok {
		return x.HasOne
	}
	return nil
}

func (m *GormFieldOptions) GetBelongsTo() *BelongsToOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_BelongsTo); ok {
		return x.BelongsTo
	}
	return nil
}

func (m *GormFieldOptions) GetHasMany() *HasManyOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_HasMany); ok {
		return x.HasMany
	}
	return nil
}

func (m *GormFieldOptions) GetManyToMany() *ManyToManyOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_ManyToMany); ok {
		return x.ManyToMany
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GormFieldOptions) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GormFieldOptions_OneofMarshaler, _GormFieldOptions_OneofUnmarshaler, _GormFieldOptions_OneofSizer, []interface{}{
		(*GormFieldOptions_HasOne)(nil),
		(*GormFieldOptions_BelongsTo)(nil),
		(*GormFieldOptions_HasMany)(nil),
		(*GormFieldOptions_ManyToMany)(nil),
	}
}

func _GormFieldOptions_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GormFieldOptions)
	// association
	switch x := m.Association.(type) {
	case *GormFieldOptions_HasOne:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasOne); err != nil {
			return err
		}
	case *GormFieldOptions_BelongsTo:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BelongsTo); err != nil {
			return err
		}
	case *GormFieldOptions_HasMany:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasMany); err != nil {
			return err
		}
	case *GormFieldOptions_ManyToMany:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ManyToMany); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GormFieldOptions.Association has unexpected type %T", x)
	}
	return nil
}

func _GormFieldOptions_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GormFieldOptions)
	switch tag {
	case 3: // association.has_one
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasOneOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_HasOne{msg}
		return true, err
	case 4: // association.belongs_to
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BelongsToOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_BelongsTo{msg}
		return true, err
	case 5: // association.has_many
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasManyOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_HasMany{msg}
		return true, err
	case 6: // association.many_to_many
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ManyToManyOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_ManyToMany{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GormFieldOptions_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GormFieldOptions)
	// association
	switch x := m.Association.(type) {
	case *GormFieldOptions_HasOne:
		s := proto.Size(x.HasOne)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GormFieldOptions_BelongsTo:
		s := proto.Size(x.BelongsTo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GormFieldOptions_HasMany:
		s := proto.Size(x.HasMany)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GormFieldOptions_ManyToMany:
		s := proto.Size(x.ManyToMany)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GormTag struct {
	Column           *string `protobuf:"bytes,1,opt,name=column" json:"column,omitempty"`
	Type             *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Size_            *int32  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Precision        *int32  `protobuf:"varint,4,opt,name=precision" json:"precision,omitempty"`
	PrimaryKey       *bool   `protobuf:"varint,5,opt,name=primary_key,json=primaryKey" json:"primary_key,omitempty"`
	Unique           *bool   `protobuf:"varint,6,opt,name=unique" json:"unique,omitempty"`
	Default          *string `protobuf:"bytes,7,opt,name=default" json:"default,omitempty"`
	NotNull          *bool   `protobuf:"varint,8,opt,name=not_null,json=notNull" json:"not_null,omitempty"`
	AutoIncrement    *bool   `protobuf:"varint,9,opt,name=auto_increment,json=autoIncrement" json:"auto_increment,omitempty"`
	Index            *string `protobuf:"bytes,10,opt,name=index" json:"index,omitempty"`
	UniqueIndex      *string `protobuf:"bytes,11,opt,name=unique_index,json=uniqueIndex" json:"unique_index,omitempty"`
	Embedded         *bool   `protobuf:"varint,12,opt,name=embedded" json:"embedded,omitempty"`
	EmbeddedPrefix   *string `protobuf:"bytes,13,opt,name=embedded_prefix,json=embeddedPrefix" json:"embedded_prefix,omitempty"`
	Ignore           *bool   `protobuf:"varint,14,opt,name=ignore" json:"ignore,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GormTag) Reset()                    { *m = GormTag{} }
func (m *GormTag) String() string            { return proto.CompactTextString(m) }
func (*GormTag) ProtoMessage()               {}
func (*GormTag) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{4} }

func (m *GormTag) GetColumn() string {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return ""
}

func (m *GormTag) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GormTag) GetSize_() int32 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

func (m *GormTag) GetPrecision() int32 {
	if m != nil && m.Precision != nil {
		return *m.Precision
	}
	return 0
}

func (m *GormTag) GetPrimaryKey() bool {
	if m != nil && m.PrimaryKey != nil {
		return *m.PrimaryKey
	}
	return false
}

func (m *GormTag) GetUnique() bool {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return false
}

func (m *GormTag) GetDefault() string {
	if m != nil && m.Default != nil {
		return *m.Default
	}
	return ""
}

func (m *GormTag) GetNotNull() bool {
	if m != nil && m.NotNull != nil {
		return *m.NotNull
	}
	return false
}

func (m *GormTag) GetAutoIncrement() bool {
	if m != nil && m.AutoIncrement != nil {
		return *m.AutoIncrement
	}
	return false
}

func (m *GormTag) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

func (m *GormTag) GetUniqueIndex() string {
	if m != nil && m.UniqueIndex != nil {
		return *m.UniqueIndex
	}
	return ""
}

func (m *GormTag) GetEmbedded() bool {
	if m != nil && m.Embedded != nil {
		return *m.Embedded
	}
	return false
}

func (m *GormTag) GetEmbeddedPrefix() string {
	if m != nil && m.EmbeddedPrefix != nil {
		return *m.EmbeddedPrefix
	}
	return ""
}

func (m *GormTag) GetIgnore() bool {
	if m != nil && m.Ignore != nil {
		return *m.Ignore
	}
	return false
}

type HasOneOptions struct {
	Foreignkey            *string  `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	ForeignkeyTag         *GormTag `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey *string  `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *HasOneOptions) Reset()                    { *m = HasOneOptions{} }
func (m *HasOneOptions) String() string            { return proto.CompactTextString(m) }
func (*HasOneOptions) ProtoMessage()               {}
func (*HasOneOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{5} }

func (m *HasOneOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *HasOneOptions) GetForeignkeyTag() *GormTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *HasOneOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

type BelongsToOptions struct {
	Foreignkey            *string  `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	ForeignkeyTag         *GormTag `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey *string  `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *BelongsToOptions) Reset()                    { *m = BelongsToOptions{} }
func (m *BelongsToOptions) String() string            { return proto.CompactTextString(m) }
func (*BelongsToOptions) ProtoMessage()               {}
func (*BelongsToOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{6} }

func (m *BelongsToOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *BelongsToOptions) GetForeignkeyTag() *GormTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *BelongsToOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

type HasManyOptions struct {
	Foreignkey            *string  `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	ForeignkeyTag         *GormTag `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey *string  `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	PositionField         *string  `protobuf:"bytes,4,opt,name=position_field,json=positionField" json:"position_field,omitempty"`
	PositionFieldTag      *GormTag `protobuf:"bytes,5,opt,name=position_field_tag,json=positionFieldTag" json:"position_field_tag,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *HasManyOptions) Reset()                    { *m = HasManyOptions{} }
func (m *HasManyOptions) String() string            { return proto.CompactTextString(m) }
func (*HasManyOptions) ProtoMessage()               {}
func (*HasManyOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{7} }

func (m *HasManyOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *HasManyOptions) GetForeignkeyTag() *GormTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *HasManyOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *HasManyOptions) GetPositionField() string {
	if m != nil && m.PositionField != nil {
		return *m.PositionField
	}
	return ""
}

func (m *HasManyOptions) GetPositionFieldTag() *GormTag {
	if m != nil {
		return m.PositionFieldTag
	}
	return nil
}

type ManyToManyOptions struct {
	Jointable                      *string `protobuf:"bytes,1,opt,name=jointable" json:"jointable,omitempty"`
	Foreignkey                     *string `protobuf:"bytes,2,opt,name=foreignkey" json:"foreignkey,omitempty"`
	JointableForeignkey            *string `protobuf:"bytes,3,opt,name=jointable_foreignkey,json=jointableForeignkey" json:"jointable_foreignkey,omitempty"`
	AssociationForeignkey          *string `protobuf:"bytes,4,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	AssociationJointableForeignkey *string `protobuf:"bytes,5,opt,name=association_jointable_foreignkey,json=associationJointableForeignkey" json:"association_jointable_foreignkey,omitempty"`
	XXX_unrecognized               []byte  `json:"-"`
}

func (m *ManyToManyOptions) Reset()                    { *m = ManyToManyOptions{} }
func (m *ManyToManyOptions) String() string            { return proto.CompactTextString(m) }
func (*ManyToManyOptions) ProtoMessage()               {}
func (*ManyToManyOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{8} }

func (m *ManyToManyOptions) GetJointable() string {
	if m != nil && m.Jointable != nil {
		return *m.Jointable
	}
	return ""
}

func (m *ManyToManyOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetJointableForeignkey() string {
	if m != nil && m.JointableForeignkey != nil {
		return *m.JointableForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationJointableForeignkey() string {
	if m != nil && m.AssociationJointableForeignkey != nil {
		return *m.AssociationJointableForeignkey
	}
	return ""
}

type AutoServerOptions struct {
	Autogen          *bool  `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	TxnMiddleware    *bool  `protobuf:"varint,2,opt,name=txn_middleware,json=txnMiddleware" json:"txn_middleware,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AutoServerOptions) Reset()                    { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string            { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()               {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{9} }

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

func (m *AutoServerOptions) GetTxnMiddleware() bool {
	if m != nil && m.TxnMiddleware != nil {
		return *m.TxnMiddleware
	}
	return false
}

type MethodOptions struct {
	ObjectType       *string `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MethodOptions) Reset()                    { *m = MethodOptions{} }
func (m *MethodOptions) String() string            { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()               {}
func (*MethodOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{10} }

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*GormFileOptions)(nil),
	Field:         52119,
	Name:          "gorm.file_opts",
	Tag:           "bytes,52119,opt,name=file_opts,json=fileOpts",
	Filename:      "options/gorm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*GormMessageOptions)(nil),
	Field:         52119,
	Name:          "gorm.opts",
	Tag:           "bytes,52119,opt,name=opts",
	Filename:      "options/gorm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*GormFieldOptions)(nil),
	Field:         52119,
	Name:          "gorm.field",
	Tag:           "bytes,52119,opt,name=field",
	Filename:      "options/gorm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         52119,
	Name:          "gorm.server",
	Tag:           "bytes,52119,opt,name=server",
	Filename:      "options/gorm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         52119,
	Name:          "gorm.method",
	Tag:           "bytes,52119,opt,name=method",
	Filename:      "options/gorm.proto",
}

func init() {
	proto.RegisterType((*GormFileOptions)(nil), "gorm.GormFileOptions")
	proto.RegisterType((*GormMessageOptions)(nil), "gorm.GormMessageOptions")
	proto.RegisterType((*ExtraField)(nil), "gorm.ExtraField")
	proto.RegisterType((*GormFieldOptions)(nil), "gorm.GormFieldOptions")
	proto.RegisterType((*GormTag)(nil), "gorm.GormTag")
	proto.RegisterType((*HasOneOptions)(nil), "gorm.HasOneOptions")
	proto.RegisterType((*BelongsToOptions)(nil), "gorm.BelongsToOptions")
	proto.RegisterType((*HasManyOptions)(nil), "gorm.HasManyOptions")
	proto.RegisterType((*ManyToManyOptions)(nil), "gorm.ManyToManyOptions")
	proto.RegisterType((*AutoServerOptions)(nil), "gorm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "gorm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("options/gorm.proto", fileDescriptorGorm) }

var fileDescriptorGorm = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0x27, 0xd9, 0xfc, 0x71, 0x5e, 0xd6, 0xe9, 0x76, 0xba, 0x5d, 0x4c, 0x55, 0x76, 0x83, 0x11,
	0x62, 0x85, 0xd4, 0x84, 0xae, 0x0a, 0x48, 0xd9, 0x53, 0x57, 0x62, 0xd9, 0x82, 0xc2, 0xa2, 0x21,
	0x5c, 0xb8, 0x58, 0x8e, 0x3d, 0xf1, 0x4e, 0xb1, 0x67, 0xcc, 0x78, 0x0c, 0x09, 0x37, 0x0e, 0x7c,
	0x01, 0x24, 0xd4, 0x0b, 0x12, 0x1f, 0x81, 0xaf, 0x88, 0x66, 0xc6, 0xff, 0xd2, 0xa4, 0x9c, 0x7b,
	0x9b, 0xf7, 0x7b, 0xef, 0xfd, 0xde, 0x9f, 0x79, 0x9e, 0x67, 0x40, 0x3c, 0x95, 0x94, 0xb3, 0x6c,
	0x1a, 0x71, 0x91, 0x4c, 0x52, 0xc1, 0x25, 0x47, 0x1d, 0x75, 0x7e, 0x34, 0x8e, 0x38, 0x8f, 0x62,
	0x32, 0xd5, 0xd8, 0x32, 0x5f, 0x4d, 0x43, 0x92, 0x05, 0x82, 0xa6, 0x92, 0x0b, 0x63, 0xe7, 0xde,
	0x87, 0x7b, 0x5f, 0x71, 0x91, 0x5c, 0xd3, 0x98, 0xdc, 0x1a, 0x16, 0xf7, 0xaf, 0x16, 0x20, 0x85,
	0xcd, 0x49, 0x96, 0xf9, 0x51, 0x09, 0x23, 0x07, 0xfa, 0x5c, 0x24, 0xfe, 0x32, 0x26, 0x4e, 0x6b,
	0xdc, 0x3e, 0xb7, 0x70, 0x29, 0xa2, 0x4f, 0xa0, 0x4f, 0x59, 0x10, 0xe7, 0x21, 0x71, 0xda, 0xe3,
	0x83, 0xf3, 0xe1, 0xc5, 0xd1, 0x44, 0x67, 0xf2, 0xe5, 0x5a, 0x0a, 0xff, 0x9a, 0x92, 0x38, 0xc4,
	0xa5, 0x01, 0x3a, 0x86, 0xae, 0xd4, 0x1c, 0x07, 0xe3, 0xd6, 0xf9, 0x00, 0x1b, 0x01, 0x7d, 0x08,
	0x76, 0x92, 0xc7, 0x92, 0x7a, 0x7e, 0x10, 0xf0, 0x9c, 0x49, 0xa7, 0x33, 0x6e, 0x9d, 0x5b, 0xf8,
	0x50, 0x83, 0xcf, 0x0d, 0xe6, 0xfe, 0x00, 0x50, 0x33, 0x22, 0x04, 0x1d, 0xb9, 0x49, 0x4d, 0x2e,
	0x03, 0xac, 0xcf, 0x0a, 0x63, 0x7e, 0xa2, 0xb2, 0xd0, 0x98, 0x3a, 0xa3, 0x33, 0x38, 0x90, 0x7e,
	0xa4, 0xc3, 0x0d, 0x2f, 0x6c, 0x93, 0x98, 0xaa, 0x6e, 0xe1, 0x47, 0x58, 0x69, 0xdc, 0x7f, 0xdb,
	0x70, 0x64, 0x5a, 0x40, 0xe2, 0xb0, 0x2c, 0xb6, 0xf0, 0x6a, 0xbd, 0xc9, 0x4b, 0x85, 0x0a, 0x05,
	0x4f, 0x9d, 0xb6, 0x4e, 0x54, 0x9f, 0xd1, 0x04, 0xfa, 0x77, 0x7e, 0xe6, 0x71, 0x46, 0x8a, 0x70,
	0x0f, 0x8c, 0xe3, 0x8d, 0x9f, 0xdd, 0xb2, 0xb2, 0x8f, 0x37, 0xef, 0xe0, 0xde, 0x9d, 0x06, 0xd0,
	0x17, 0x00, 0x4b, 0x12, 0x73, 0x16, 0x65, 0x9e, 0xe4, 0xba, 0xe4, 0xe1, 0xc5, 0x89, 0x71, 0xb9,
	0x32, 0xf8, 0x82, 0xd7, 0x5e, 0x83, 0x65, 0x89, 0xa1, 0xa7, 0x60, 0xa9, 0x40, 0x89, 0xcf, 0x36,
	0x4e, 0x57, 0xbb, 0x1d, 0x57, 0x91, 0xe6, 0x3e, 0xdb, 0xd4, 0x4e, 0x2a, 0x21, 0x85, 0xa0, 0x4b,
	0x38, 0x54, 0xe6, 0x9e, 0xe4, 0xc6, 0xad, 0xa7, 0xdd, 0xde, 0x35, 0x6e, 0xca, 0x62, 0xc1, 0xb7,
	0x3d, 0x21, 0xa9, 0xc0, 0x2b, 0x1b, 0x86, 0x7e, 0x96, 0xf1, 0x80, 0xfa, 0x4a, 0xeb, 0xfe, 0x79,
	0x00, 0xfd, 0xa2, 0x19, 0xe8, 0x04, 0x7a, 0x01, 0x8f, 0xf3, 0x84, 0xe9, 0x5e, 0x0d, 0x70, 0x21,
	0x55, 0xd7, 0xd3, 0xd6, 0x68, 0x75, 0x3d, 0x19, 0xfd, 0xcd, 0x34, 0xa7, 0x8b, 0xf5, 0x19, 0x3d,
	0x86, 0x41, 0x2a, 0x48, 0x40, 0x33, 0xca, 0x99, 0x6e, 0x41, 0x17, 0xd7, 0x00, 0x3a, 0x83, 0x61,
	0x2a, 0x68, 0xe2, 0x8b, 0x8d, 0xf7, 0x13, 0x31, 0xb5, 0x5a, 0x18, 0x0a, 0xe8, 0x1b, 0xb2, 0x51,
	0xe1, 0x73, 0x46, 0x7f, 0xce, 0x89, 0x2e, 0xc8, 0xc2, 0x85, 0xa4, 0x86, 0x35, 0x24, 0x2b, 0x3f,
	0x8f, 0xa5, 0xd3, 0xd7, 0x19, 0x94, 0x22, 0x7a, 0x0f, 0x2c, 0xc6, 0xa5, 0xc7, 0xf2, 0x38, 0x76,
	0x2c, 0xed, 0xd3, 0x67, 0x5c, 0x7e, 0x9b, 0xc7, 0x31, 0xfa, 0x08, 0x46, 0x7e, 0x2e, 0xb9, 0x47,
	0x59, 0x20, 0x48, 0x42, 0x98, 0x74, 0x06, 0xda, 0xc0, 0x56, 0xe8, 0x8b, 0x12, 0x54, 0x23, 0x4c,
	0x59, 0x48, 0xd6, 0x0e, 0x98, 0x11, 0xd6, 0x02, 0xfa, 0x00, 0x0e, 0x4d, 0x6c, 0xcf, 0x28, 0x87,
	0x5a, 0x39, 0x34, 0xd8, 0x0b, 0x6d, 0xf2, 0x08, 0x2c, 0x92, 0x2c, 0x49, 0x18, 0x92, 0xd0, 0x39,
	0xd4, 0xcc, 0x95, 0x8c, 0x3e, 0x86, 0x7b, 0xe5, 0xd9, 0x4b, 0x05, 0x59, 0xd1, 0xb5, 0x63, 0x6b,
	0x86, 0x51, 0x09, 0x7f, 0xa7, 0x51, 0x55, 0x31, 0x8d, 0x18, 0x17, 0xc4, 0x19, 0x99, 0x8a, 0x8d,
	0xe4, 0xfe, 0xdd, 0x02, 0x7b, 0x6b, 0xd0, 0xd0, 0x29, 0xc0, 0x8a, 0x0b, 0x42, 0x23, 0xa6, 0x7a,
	0x67, 0xae, 0xa7, 0x81, 0xa0, 0x67, 0x30, 0xaa, 0x25, 0x4f, 0x8d, 0x7b, 0x7b, 0xdf, 0xb8, 0xdb,
	0xb5, 0x91, 0xba, 0xf0, 0xcf, 0xe0, 0xa4, 0x31, 0x0b, 0x5e, 0x23, 0x82, 0xf9, 0xa2, 0x1f, 0x36,
	0xb4, 0xd7, 0x95, 0xd2, 0xfd, 0xa7, 0x05, 0x47, 0xaf, 0x0f, 0xf5, 0xdb, 0x95, 0xe1, 0xef, 0x6d,
	0x18, 0x6d, 0x7f, 0x3f, 0x6f, 0x55, 0x7e, 0x6a, 0x3a, 0x53, 0x9e, 0x51, 0xe3, 0xa3, 0xde, 0x2a,
	0xfd, 0xb9, 0x0c, 0xb0, 0x5d, 0xa2, 0xe6, 0x5d, 0xbc, 0x04, 0xb4, 0x6d, 0xa6, 0xf3, 0xea, 0xee,
	0xcb, 0xeb, 0x68, 0xcb, 0x73, 0xe1, 0x47, 0xee, 0x1f, 0x6d, 0xb8, 0xbf, 0xf3, 0x18, 0xa8, 0x6f,
	0xf4, 0x25, 0xa7, 0x4c, 0x16, 0x6f, 0xbf, 0x0a, 0x5a, 0x03, 0xaf, 0x35, 0xa9, 0xbd, 0xd3, 0xa4,
	0xa7, 0x70, 0x5c, 0x19, 0xef, 0x16, 0xfb, 0xa0, 0xd2, 0x35, 0x4a, 0x7d, 0x73, 0x87, 0x3a, 0xff,
	0xd7, 0xa1, 0x1b, 0x18, 0x37, 0xdd, 0xf6, 0x46, 0xed, 0x6a, 0x82, 0xd3, 0x86, 0xdd, 0xd7, 0xbb,
	0x09, 0xb8, 0x0b, 0xb8, 0xff, 0x3c, 0x97, 0xfc, 0x7b, 0x22, 0x7e, 0x21, 0xa2, 0xb1, 0x00, 0xd5,
	0x43, 0x10, 0x11, 0xf3, 0xd6, 0x59, 0xb8, 0x14, 0xd5, 0xd5, 0xc8, 0x35, 0xf3, 0x12, 0x1a, 0x86,
	0x31, 0xf9, 0xd5, 0x17, 0xa4, 0x58, 0x0b, 0xb6, 0x5c, 0xb3, 0x79, 0x05, 0xba, 0x9f, 0x82, 0x3d,
	0x27, 0xf2, 0x8e, 0x37, 0xb6, 0xcc, 0x90, 0x2f, 0x5f, 0x92, 0x40, 0x7a, 0xc5, 0x2a, 0xd3, 0xbd,
	0x33, 0xd0, 0x62, 0x93, 0x92, 0x19, 0x86, 0xc1, 0x8a, 0xc6, 0xc4, 0xe3, 0xa9, 0xcc, 0xd0, 0xe3,
	0x89, 0xd9, 0xe6, 0x93, 0x72, 0x9b, 0x4f, 0x1a, 0x5b, 0xdb, 0x79, 0xf5, 0xca, 0xec, 0x9c, 0x87,
	0xf5, 0x1d, 0x37, 0xd4, 0xd8, 0x5a, 0x19, 0x21, 0x9b, 0xdd, 0x42, 0x47, 0xd3, 0x9d, 0xed, 0xd0,
	0x6d, 0x2f, 0xfc, 0x8a, 0xd1, 0xa9, 0x19, 0xb7, 0x2d, 0xb0, 0x26, 0x9a, 0xcd, 0xa1, 0xab, 0x07,
	0x0d, 0xbd, 0xbf, 0x27, 0xc1, 0x7a, 0xa7, 0x56, 0x7c, 0x27, 0xcd, 0x0c, 0x6b, 0x3d, 0x36, 0x2c,
	0x33, 0x0c, 0xbd, 0x4c, 0xf7, 0x7d, 0x4f, 0x86, 0xea, 0x42, 0x68, 0xb0, 0x93, 0x61, 0xb1, 0xc6,
	0x76, 0xae, 0x0c, 0x17, 0x4c, 0xb3, 0x39, 0xf4, 0x12, 0xdd, 0x79, 0x74, 0xba, 0xa7, 0xea, 0xc6,
	0x95, 0x54, 0x94, 0xc5, 0xea, 0xde, 0x52, 0xe2, 0x82, 0xe4, 0xea, 0xf3, 0x1f, 0x9f, 0x45, 0x54,
	0xde, 0xe5, 0xcb, 0x49, 0xc0, 0x93, 0x29, 0x65, 0x2b, 0xbe, 0x8c, 0xf9, 0x9a, 0xa7, 0x84, 0x99,
	0x3f, 0xad, 0xe0, 0x49, 0x44, 0xd8, 0x13, 0x45, 0x30, 0x2d, 0x7e, 0xcd, 0x2e, 0x95, 0xf0, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x83, 0x1b, 0x1f, 0xa9, 0x09, 0x00, 0x00,
}
