// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: options/gorm.proto

/*
Package gorm is a generated protocol buffer package.

It is generated from these files:
	options/gorm.proto

It has these top-level messages:
	GormFileOptions
	GormMessageOptions
	ExtraField
	GormFieldOptions
	AutoServerOptions
	MethodOptions
*/
package gorm

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GormFileOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GormFileOptions) Reset()                    { *m = GormFileOptions{} }
func (m *GormFileOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFileOptions) ProtoMessage()               {}
func (*GormFileOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{0} }

type GormMessageOptions struct {
	Ormable          *bool         `protobuf:"varint,1,req,name=ormable" json:"ormable,omitempty"`
	Include          []*ExtraField `protobuf:"bytes,2,rep,name=include" json:"include,omitempty"`
	Table            *string       `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	MultiTenant      *bool         `protobuf:"varint,4,opt,name=multi_tenant,json=multiTenant" json:"multi_tenant,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GormMessageOptions) Reset()                    { *m = GormMessageOptions{} }
func (m *GormMessageOptions) String() string            { return proto.CompactTextString(m) }
func (*GormMessageOptions) ProtoMessage()               {}
func (*GormMessageOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{1} }

func (m *GormMessageOptions) GetOrmable() bool {
	if m != nil && m.Ormable != nil {
		return *m.Ormable
	}
	return false
}

func (m *GormMessageOptions) GetInclude() []*ExtraField {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *GormMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GormMessageOptions) GetMultiTenant() bool {
	if m != nil && m.MultiTenant != nil {
		return *m.MultiTenant
	}
	return false
}

type ExtraField struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Tags             *string `protobuf:"bytes,3,opt,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExtraField) Reset()                    { *m = ExtraField{} }
func (m *ExtraField) String() string            { return proto.CompactTextString(m) }
func (*ExtraField) ProtoMessage()               {}
func (*ExtraField) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{2} }

func (m *ExtraField) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ExtraField) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ExtraField) GetTags() string {
	if m != nil && m.Tags != nil {
		return *m.Tags
	}
	return ""
}

type GormFieldOptions struct {
	Tags             *string `protobuf:"bytes,1,opt,name=tags" json:"tags,omitempty"`
	Drop             *bool   `protobuf:"varint,2,opt,name=drop" json:"drop,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GormFieldOptions) Reset()                    { *m = GormFieldOptions{} }
func (m *GormFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFieldOptions) ProtoMessage()               {}
func (*GormFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{3} }

func (m *GormFieldOptions) GetTags() string {
	if m != nil && m.Tags != nil {
		return *m.Tags
	}
	return ""
}

func (m *GormFieldOptions) GetDrop() bool {
	if m != nil && m.Drop != nil {
		return *m.Drop
	}
	return false
}

type AutoServerOptions struct {
	Autogen          *bool  `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AutoServerOptions) Reset()                    { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string            { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()               {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{4} }

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

type MethodOptions struct {
	ObjectType       *string `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MethodOptions) Reset()                    { *m = MethodOptions{} }
func (m *MethodOptions) String() string            { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()               {}
func (*MethodOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{5} }

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*GormFileOptions)(nil),
	Field:         52119,
	Name:          "gorm.file_opts",
	Tag:           "bytes,52119,opt,name=file_opts,json=fileOpts",
	Filename:      "options/gorm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*GormMessageOptions)(nil),
	Field:         52119,
	Name:          "gorm.opts",
	Tag:           "bytes,52119,opt,name=opts",
	Filename:      "options/gorm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*GormFieldOptions)(nil),
	Field:         52119,
	Name:          "gorm.field",
	Tag:           "bytes,52119,opt,name=field",
	Filename:      "options/gorm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         52119,
	Name:          "gorm.server",
	Tag:           "bytes,52119,opt,name=server",
	Filename:      "options/gorm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         52119,
	Name:          "gorm.method",
	Tag:           "bytes,52119,opt,name=method",
	Filename:      "options/gorm.proto",
}

func init() {
	proto.RegisterType((*GormFileOptions)(nil), "gorm.GormFileOptions")
	proto.RegisterType((*GormMessageOptions)(nil), "gorm.GormMessageOptions")
	proto.RegisterType((*ExtraField)(nil), "gorm.ExtraField")
	proto.RegisterType((*GormFieldOptions)(nil), "gorm.GormFieldOptions")
	proto.RegisterType((*AutoServerOptions)(nil), "gorm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "gorm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("options/gorm.proto", fileDescriptorGorm) }

var fileDescriptorGorm = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xe5, 0x34, 0x4d, 0x93, 0x09, 0x88, 0x76, 0xf9, 0x67, 0x21, 0xa0, 0xc6, 0xa7, 0x08,
	0x09, 0x07, 0xf5, 0xe8, 0x1b, 0x48, 0x14, 0x2e, 0x51, 0xa5, 0xa5, 0x27, 0x2e, 0x91, 0x13, 0x4f,
	0x8c, 0x91, 0xed, 0xb1, 0x76, 0xd7, 0x88, 0x7e, 0x0e, 0x0e, 0xf9, 0xba, 0x68, 0x67, 0xe3, 0xd8,
	0x21, 0xb9, 0xcd, 0x3c, 0x4f, 0x7e, 0xfb, 0x66, 0x9e, 0x02, 0x82, 0x6a, 0x93, 0x53, 0xa5, 0xe7,
	0x19, 0xa9, 0x32, 0xaa, 0x15, 0x19, 0x12, 0x43, 0x5b, 0xbf, 0x0a, 0x32, 0xa2, 0xac, 0xc0, 0x39,
	0x6b, 0xab, 0x66, 0x33, 0x4f, 0x51, 0xaf, 0x55, 0x5e, 0x1b, 0x52, 0x6e, 0x2e, 0xbc, 0x82, 0x27,
	0x5f, 0x49, 0x95, 0xb7, 0x79, 0x81, 0x77, 0x8e, 0x12, 0xfe, 0xf5, 0x40, 0x58, 0x6d, 0x81, 0x5a,
	0x27, 0x59, 0x2b, 0x0b, 0x1f, 0x2e, 0x48, 0x95, 0xc9, 0xaa, 0x40, 0xdf, 0x0b, 0x06, 0xb3, 0xb1,
	0x6c, 0x5b, 0xf1, 0x1e, 0x2e, 0xf2, 0x6a, 0x5d, 0x34, 0x29, 0xfa, 0x83, 0xe0, 0x6c, 0x36, 0xbd,
	0xb9, 0x8c, 0xd8, 0xc9, 0x97, 0x3f, 0x46, 0x25, 0xb7, 0x39, 0x16, 0xa9, 0x6c, 0x07, 0xc4, 0x33,
	0x38, 0x37, 0xcc, 0x38, 0x0b, 0xbc, 0xd9, 0x44, 0xba, 0x46, 0xbc, 0x83, 0x47, 0x65, 0x53, 0x98,
	0x7c, 0x69, 0xb0, 0x4a, 0x2a, 0xe3, 0x0f, 0x03, 0x6f, 0x36, 0x96, 0x53, 0xd6, 0xee, 0x59, 0x0a,
	0xbf, 0x01, 0x74, 0x3c, 0x21, 0x60, 0x68, 0x1e, 0x6a, 0xe7, 0x64, 0x22, 0xb9, 0xb6, 0x5a, 0x95,
	0x94, 0xd6, 0x03, 0x6b, 0xb6, 0xe6, 0xb9, 0x24, 0xd3, 0xbb, 0xd7, 0xb8, 0x0e, 0x63, 0xb8, 0x74,
	0x2b, 0x63, 0x91, 0xb6, 0xcb, 0xb5, 0x73, 0x5e, 0x37, 0x67, 0xb5, 0x54, 0x51, 0xed, 0x0f, 0xd8,
	0x0c, 0xd7, 0xe1, 0x07, 0xb8, 0xfa, 0xd4, 0x18, 0xfa, 0x8e, 0xea, 0x37, 0xaa, 0xde, 0x65, 0x92,
	0xc6, 0x50, 0x86, 0x15, 0xff, 0x7e, 0x2c, 0xdb, 0x36, 0xfc, 0x08, 0x8f, 0x17, 0x68, 0x7e, 0xd2,
	0xfe, 0x9d, 0x6b, 0x98, 0xd2, 0xea, 0x17, 0xae, 0xcd, 0x72, 0x67, 0xdf, 0x3e, 0x07, 0x4e, 0xba,
	0x7f, 0xa8, 0x31, 0x96, 0x30, 0xd9, 0xe4, 0x05, 0x2e, 0xa9, 0x36, 0x5a, 0xbc, 0x8e, 0x5c, 0x7e,
	0x51, 0x9b, 0x5f, 0xd4, 0xcb, 0xc9, 0xdf, 0x6e, 0xed, 0x56, 0xd3, 0x9b, 0xe7, 0xee, 0xda, 0xff,
	0xc5, 0x28, 0xc7, 0x1b, 0xd7, 0xe8, 0xf8, 0x0e, 0x86, 0x8c, 0xbb, 0x3e, 0xc2, 0x1d, 0x46, 0xbc,
	0x27, 0xfa, 0x1d, 0xf1, 0x70, 0x42, 0x32, 0x28, 0x5e, 0xc0, 0xf9, 0x86, 0x63, 0x78, 0x73, 0xc2,
	0x60, 0x77, 0xd5, 0x3d, 0xef, 0x45, 0xdf, 0x61, 0xf7, 0x5d, 0x3a, 0x4a, 0x2c, 0x61, 0xa4, 0xf9,
	0xa0, 0x27, 0x1c, 0xda, 0x4b, 0xe7, 0xeb, 0x23, 0x87, 0x2f, 0x1d, 0xf1, 0x28, 0x0b, 0xb9, 0x23,
	0xc5, 0x0b, 0x18, 0x95, 0x7c, 0x79, 0xf1, 0xf6, 0xc4, 0xd6, 0xbd, 0x48, 0xf6, 0xc8, 0xa7, 0x0e,
	0x79, 0xf0, 0x51, 0xee, 0x20, 0x9f, 0x47, 0x3f, 0xf8, 0x0f, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x36, 0xa2, 0x17, 0x1a, 0x6b, 0x03, 0x00, 0x00,
}
