// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/feature_demo/demo_multi_file_service.proto

package example

import context "context"

import gorm1 "github.com/jinzhu/gorm"
import json1 "encoding/json"
import trace1 "go.opencensus.io/trace"

import fmt "fmt"
import math "math"
import _ "github.com/infobloxopen/atlas-app-toolkit/query"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlogPostServiceDefaultServer struct {
	DB *gorm1.DB
}

// Read ...
func (m *BlogPostServiceDefaultServer) Read(ctx context.Context, in *ReadAccountRequest) (*ReadBlogPostsResponse, error) {
	_, span := trace1.StartSpan(ctx, "Read")
	defer span.End()
	rawParameterIn, errMarshalingIn := json1.Marshal(in)
	if errMarshalingIn != nil {
		span.Annotate([]trace1.Attribute{trace1.StringAttribute("in", nil)}, "in parameter")
		return nil, errMarshalingIn
	}
	span.Annotate([]trace1.Attribute{trace1.StringAttribute("in", rawParameterIn)}, "in parameter")
	out := &ReadBlogPostsResponse{}
	rawParameterOut, errMarshalingOut := json1.Marshal(out)
	if errMarshalingOut != nil {
		span.Annotate([]trace1.Attribute{trace1.StringAttribute("out", nil)}, "out parameter")
		return nil, errMarshalingOut
	}
	span.Annotate([]trace1.Attribute{trace1.StringAttribute("out", rawParameterOut)}, "out parameter")
	return out, nil
}
