// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/feature_demo/demo_types.proto

package example // import "github.com/infobloxopen/protoc-gen-gorm/example/feature_demo"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import user "github.com/infobloxopen/protoc-gen-gorm/example/user"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"
import types "github.com/infobloxopen/protoc-gen-gorm/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enums are mapped to the their underlying numeric value in the db.
// This is practical from an API perspective, but tougher for debugging.
// Strings with validation constraints can be used instead if desired
type TestTypesStatus int32

const (
	TestTypes_UNKNOWN TestTypesStatus = 0
	TestTypes_GOOD    TestTypesStatus = 1
	TestTypes_BAD     TestTypesStatus = 2
)

var TestTypesStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "GOOD",
	2: "BAD",
}
var TestTypesStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"GOOD":    1,
	"BAD":     2,
}

func (x TestTypesStatus) String() string {
	return proto.EnumName(TestTypesStatus_name, int32(x))
}
func (TestTypesStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{0, 0}
}

// test_types is a message that includes a representative sample of the
// available types
type TestTypes struct {
	// the (gorm.field).drop option allows for setting a field to be API only
	ApiOnlyString string `protobuf:"bytes,1,opt,name=api_only_string,json=apiOnlyString" json:"api_only_string,omitempty"`
	// repeated raw types are currently unsupported, so this field will be dropped
	// at the ORM level
	Numbers []int32 `protobuf:"varint,2,rep,packed,name=numbers" json:"numbers,omitempty"`
	// a StringValue represents a Nullable string
	OptionalString *wrappers.StringValue `protobuf:"bytes,3,opt,name=optional_string,json=optionalString" json:"optional_string,omitempty"`
	BecomesInt     TestTypesStatus       `protobuf:"varint,4,opt,name=becomes_int,json=becomesInt,enum=example.TestTypesStatus" json:"becomes_int,omitempty"`
	// The Empty type serves no purpose outside of rpc calls and is dropped
	// automatically from objects
	Nothingness *empty.Empty `protobuf:"bytes,5,opt,name=nothingness" json:"nothingness,omitempty"`
	// The UUID custom type should act like a StringValue at the API level, but is
	// automatically converted to and from a uuid.UUID (github.com/satori/go.uuid)
	Uuid *types.UUID `protobuf:"bytes,6,opt,name=uuid" json:"uuid,omitempty"`
	// Timestamps convert to golang's time.Time type, and created_at and
	// updated_at values are automatically filled by GORM
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// This represents a foreign key to the 'type_with_id' type for associations
	// This could be hidden from the API (or soon autogenerated).
	TypeWithIdId uint32 `protobuf:"varint,8,opt,name=type_with_id_id,json=typeWithIdId" json:"type_with_id_id,omitempty"`
	// This is an arbitrary JSON string that is marshalled and unmarshalled
	// specially in grpc-gateway as a JSON object
	JsonField *types.JSONValue `protobuf:"bytes,9,opt,name=json_field,json=jsonField" json:"json_field,omitempty"`
	// The UUIDValue custom type should act like a StringValue at the API level, but is
	// automatically converted to and from a *uuid.UUID (github.com/satori/go.uuid)
	NullableUuid         *types.UUIDValue `protobuf:"bytes,10,opt,name=nullable_uuid,json=nullableUuid" json:"nullable_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TestTypes) Reset()         { *m = TestTypes{} }
func (m *TestTypes) String() string { return proto.CompactTextString(m) }
func (*TestTypes) ProtoMessage()    {}
func (*TestTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{0}
}
func (m *TestTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestTypes.Unmarshal(m, b)
}
func (m *TestTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestTypes.Marshal(b, m, deterministic)
}
func (dst *TestTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestTypes.Merge(dst, src)
}
func (m *TestTypes) XXX_Size() int {
	return xxx_messageInfo_TestTypes.Size(m)
}
func (m *TestTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestTypes.DiscardUnknown(m)
}

var xxx_messageInfo_TestTypes proto.InternalMessageInfo

func (m *TestTypes) GetApiOnlyString() string {
	if m != nil {
		return m.ApiOnlyString
	}
	return ""
}

func (m *TestTypes) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *TestTypes) GetOptionalString() *wrappers.StringValue {
	if m != nil {
		return m.OptionalString
	}
	return nil
}

func (m *TestTypes) GetBecomesInt() TestTypesStatus {
	if m != nil {
		return m.BecomesInt
	}
	return TestTypes_UNKNOWN
}

func (m *TestTypes) GetNothingness() *empty.Empty {
	if m != nil {
		return m.Nothingness
	}
	return nil
}

func (m *TestTypes) GetUuid() *types.UUID {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *TestTypes) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TestTypes) GetTypeWithIdId() uint32 {
	if m != nil {
		return m.TypeWithIdId
	}
	return 0
}

func (m *TestTypes) GetJsonField() *types.JSONValue {
	if m != nil {
		return m.JsonField
	}
	return nil
}

func (m *TestTypes) GetNullableUuid() *types.UUIDValue {
	if m != nil {
		return m.NullableUuid
	}
	return nil
}

// TypeWithID demonstrates some basic assocation behavior
type TypeWithID struct {
	// any field named 'id' is assumed by gorm to be the primary key for the
	// object.
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The field option also allows arbitrary tag setting, such as informing
	// gorm of a primary key, different column names or different types in the db
	Ip string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// A default has-many relationship, will error on generation if no FK field,
	// convention {typename}_id, is present. These FK fields will be automatically
	// populated on create and update.
	Things []*TestTypes `protobuf:"bytes,3,rep,name=things" json:"things,omitempty"`
	// A default has-one relationship, will error as above
	ANestedObject *TestTypes `protobuf:"bytes,4,opt,name=a_nested_object,json=aNestedObject" json:"a_nested_object,omitempty"`
	// An in-package and cross-package imported type (in-package can use any
	// association type, cross-package is limited to belongs_to and many_to_many)
	Point                *IntPoint        `protobuf:"bytes,5,opt,name=point" json:"point,omitempty"`
	User                 *user.User       `protobuf:"bytes,6,opt,name=user" json:"user,omitempty"`
	Address              *types.InetValue `protobuf:"bytes,7,opt,name=address" json:"address,omitempty"`
	MultiaccountTypeIds  []uint32         `protobuf:"varint,8,rep,packed,name=multiaccount_type_ids,json=multiaccountTypeIds" json:"multiaccount_type_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TypeWithID) Reset()         { *m = TypeWithID{} }
func (m *TypeWithID) String() string { return proto.CompactTextString(m) }
func (*TypeWithID) ProtoMessage()    {}
func (*TypeWithID) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{1}
}
func (m *TypeWithID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeWithID.Unmarshal(m, b)
}
func (m *TypeWithID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeWithID.Marshal(b, m, deterministic)
}
func (dst *TypeWithID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeWithID.Merge(dst, src)
}
func (m *TypeWithID) XXX_Size() int {
	return xxx_messageInfo_TypeWithID.Size(m)
}
func (m *TypeWithID) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeWithID.DiscardUnknown(m)
}

var xxx_messageInfo_TypeWithID proto.InternalMessageInfo

func (m *TypeWithID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TypeWithID) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TypeWithID) GetThings() []*TestTypes {
	if m != nil {
		return m.Things
	}
	return nil
}

func (m *TypeWithID) GetANestedObject() *TestTypes {
	if m != nil {
		return m.ANestedObject
	}
	return nil
}

func (m *TypeWithID) GetPoint() *IntPoint {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *TypeWithID) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *TypeWithID) GetAddress() *types.InetValue {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *TypeWithID) GetMultiaccountTypeIds() []uint32 {
	if m != nil {
		return m.MultiaccountTypeIds
	}
	return nil
}

// MultiaccountTypeWithID demonstrates the generated multi-account support
type MultiaccountTypeWithID struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SomeField            string   `protobuf:"bytes,2,opt,name=some_field,json=someField" json:"some_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiaccountTypeWithID) Reset()         { *m = MultiaccountTypeWithID{} }
func (m *MultiaccountTypeWithID) String() string { return proto.CompactTextString(m) }
func (*MultiaccountTypeWithID) ProtoMessage()    {}
func (*MultiaccountTypeWithID) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{2}
}
func (m *MultiaccountTypeWithID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiaccountTypeWithID.Unmarshal(m, b)
}
func (m *MultiaccountTypeWithID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiaccountTypeWithID.Marshal(b, m, deterministic)
}
func (dst *MultiaccountTypeWithID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiaccountTypeWithID.Merge(dst, src)
}
func (m *MultiaccountTypeWithID) XXX_Size() int {
	return xxx_messageInfo_MultiaccountTypeWithID.Size(m)
}
func (m *MultiaccountTypeWithID) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiaccountTypeWithID.DiscardUnknown(m)
}

var xxx_messageInfo_MultiaccountTypeWithID proto.InternalMessageInfo

func (m *MultiaccountTypeWithID) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MultiaccountTypeWithID) GetSomeField() string {
	if m != nil {
		return m.SomeField
	}
	return ""
}

type MultiaccountTypeWithoutID struct {
	SomeField            string   `protobuf:"bytes,1,opt,name=some_field,json=someField" json:"some_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiaccountTypeWithoutID) Reset()         { *m = MultiaccountTypeWithoutID{} }
func (m *MultiaccountTypeWithoutID) String() string { return proto.CompactTextString(m) }
func (*MultiaccountTypeWithoutID) ProtoMessage()    {}
func (*MultiaccountTypeWithoutID) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{3}
}
func (m *MultiaccountTypeWithoutID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiaccountTypeWithoutID.Unmarshal(m, b)
}
func (m *MultiaccountTypeWithoutID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiaccountTypeWithoutID.Marshal(b, m, deterministic)
}
func (dst *MultiaccountTypeWithoutID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiaccountTypeWithoutID.Merge(dst, src)
}
func (m *MultiaccountTypeWithoutID) XXX_Size() int {
	return xxx_messageInfo_MultiaccountTypeWithoutID.Size(m)
}
func (m *MultiaccountTypeWithoutID) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiaccountTypeWithoutID.DiscardUnknown(m)
}

var xxx_messageInfo_MultiaccountTypeWithoutID proto.InternalMessageInfo

func (m *MultiaccountTypeWithoutID) GetSomeField() string {
	if m != nil {
		return m.SomeField
	}
	return ""
}

type APIOnlyType struct {
	// here the ormable flag is not used, so nothing will be generated for this
	// object at the ORM level, and when this type is used as a field or
	// repeated field in another message that field will be dropped in the Orm
	// model, and would have to be set by hook
	Contents             string   `protobuf:"bytes,1,opt,name=contents" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIOnlyType) Reset()         { *m = APIOnlyType{} }
func (m *APIOnlyType) String() string { return proto.CompactTextString(m) }
func (*APIOnlyType) ProtoMessage()    {}
func (*APIOnlyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{4}
}
func (m *APIOnlyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIOnlyType.Unmarshal(m, b)
}
func (m *APIOnlyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIOnlyType.Marshal(b, m, deterministic)
}
func (dst *APIOnlyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIOnlyType.Merge(dst, src)
}
func (m *APIOnlyType) XXX_Size() int {
	return xxx_messageInfo_APIOnlyType.Size(m)
}
func (m *APIOnlyType) XXX_DiscardUnknown() {
	xxx_messageInfo_APIOnlyType.DiscardUnknown(m)
}

var xxx_messageInfo_APIOnlyType proto.InternalMessageInfo

func (m *APIOnlyType) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type PrimaryUUIDType struct {
	Id                   *types.UUIDValue `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Child                *ExternalChild   `protobuf:"bytes,2,opt,name=child" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PrimaryUUIDType) Reset()         { *m = PrimaryUUIDType{} }
func (m *PrimaryUUIDType) String() string { return proto.CompactTextString(m) }
func (*PrimaryUUIDType) ProtoMessage()    {}
func (*PrimaryUUIDType) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{5}
}
func (m *PrimaryUUIDType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryUUIDType.Unmarshal(m, b)
}
func (m *PrimaryUUIDType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryUUIDType.Marshal(b, m, deterministic)
}
func (dst *PrimaryUUIDType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryUUIDType.Merge(dst, src)
}
func (m *PrimaryUUIDType) XXX_Size() int {
	return xxx_messageInfo_PrimaryUUIDType.Size(m)
}
func (m *PrimaryUUIDType) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryUUIDType.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryUUIDType proto.InternalMessageInfo

func (m *PrimaryUUIDType) GetId() *types.UUIDValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PrimaryUUIDType) GetChild() *ExternalChild {
	if m != nil {
		return m.Child
	}
	return nil
}

type PrimaryStringType struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Child                *ExternalChild `protobuf:"bytes,2,opt,name=child" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrimaryStringType) Reset()         { *m = PrimaryStringType{} }
func (m *PrimaryStringType) String() string { return proto.CompactTextString(m) }
func (*PrimaryStringType) ProtoMessage()    {}
func (*PrimaryStringType) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{6}
}
func (m *PrimaryStringType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryStringType.Unmarshal(m, b)
}
func (m *PrimaryStringType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryStringType.Marshal(b, m, deterministic)
}
func (dst *PrimaryStringType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryStringType.Merge(dst, src)
}
func (m *PrimaryStringType) XXX_Size() int {
	return xxx_messageInfo_PrimaryStringType.Size(m)
}
func (m *PrimaryStringType) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryStringType.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryStringType proto.InternalMessageInfo

func (m *PrimaryStringType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PrimaryStringType) GetChild() *ExternalChild {
	if m != nil {
		return m.Child
	}
	return nil
}

type PrimaryIncluded struct {
	Child                *ExternalChild `protobuf:"bytes,1,opt,name=child" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrimaryIncluded) Reset()         { *m = PrimaryIncluded{} }
func (m *PrimaryIncluded) String() string { return proto.CompactTextString(m) }
func (*PrimaryIncluded) ProtoMessage()    {}
func (*PrimaryIncluded) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_types_d3987903b2820e14, []int{7}
}
func (m *PrimaryIncluded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryIncluded.Unmarshal(m, b)
}
func (m *PrimaryIncluded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryIncluded.Marshal(b, m, deterministic)
}
func (dst *PrimaryIncluded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryIncluded.Merge(dst, src)
}
func (m *PrimaryIncluded) XXX_Size() int {
	return xxx_messageInfo_PrimaryIncluded.Size(m)
}
func (m *PrimaryIncluded) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryIncluded.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryIncluded proto.InternalMessageInfo

func (m *PrimaryIncluded) GetChild() *ExternalChild {
	if m != nil {
		return m.Child
	}
	return nil
}

func init() {
	proto.RegisterType((*TestTypes)(nil), "example.TestTypes")
	proto.RegisterType((*TypeWithID)(nil), "example.TypeWithID")
	proto.RegisterType((*MultiaccountTypeWithID)(nil), "example.MultiaccountTypeWithID")
	proto.RegisterType((*MultiaccountTypeWithoutID)(nil), "example.MultiaccountTypeWithoutID")
	proto.RegisterType((*APIOnlyType)(nil), "example.APIOnlyType")
	proto.RegisterType((*PrimaryUUIDType)(nil), "example.PrimaryUUIDType")
	proto.RegisterType((*PrimaryStringType)(nil), "example.PrimaryStringType")
	proto.RegisterType((*PrimaryIncluded)(nil), "example.PrimaryIncluded")
	proto.RegisterEnum("example.TestTypesStatus", TestTypesStatus_name, TestTypesStatus_value)
}

func init() {
	proto.RegisterFile("example/feature_demo/demo_types.proto", fileDescriptor_demo_types_d3987903b2820e14)
}

var fileDescriptor_demo_types_d3987903b2820e14 = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x5d, 0xe7, 0x3b, 0x37, 0x4d, 0xd3, 0x0e, 0xda, 0xc5, 0x09, 0x1f, 0x1b, 0x45, 0x94, 0x0d,
	0x15, 0x6b, 0x4b, 0x2d, 0x0f, 0x6c, 0x78, 0x40, 0x2d, 0xe9, 0x22, 0x2f, 0xa2, 0x29, 0x6e, 0xca,
	0x0a, 0x10, 0xb2, 0xfc, 0x31, 0x49, 0x67, 0x65, 0xcf, 0x18, 0xcf, 0x98, 0x6d, 0xf8, 0x31, 0xfc,
	0x8f, 0xe4, 0x8d, 0x7f, 0x86, 0x66, 0x6c, 0x67, 0x43, 0xd3, 0x4a, 0x45, 0xfb, 0x92, 0xc8, 0xbe,
	0xe7, 0x9e, 0x3b, 0xf7, 0x9e, 0x73, 0xc7, 0x70, 0x80, 0x6f, 0xdc, 0x28, 0x0e, 0xb1, 0x39, 0xc3,
	0xae, 0x48, 0x13, 0xec, 0x04, 0x38, 0x62, 0xa6, 0xfc, 0x71, 0xc4, 0x22, 0xc6, 0xdc, 0x88, 0x13,
	0x26, 0x18, 0xaa, 0xe7, 0xb0, 0xde, 0x68, 0x4e, 0xc4, 0x75, 0xea, 0x19, 0x3e, 0x8b, 0x4c, 0x42,
	0x67, 0xcc, 0x0b, 0xd9, 0x0d, 0x8b, 0x31, 0x35, 0x15, 0xce, 0x7f, 0x3e, 0xc7, 0xf4, 0xf9, 0x9c,
	0x25, 0x91, 0xc9, 0x62, 0x41, 0x18, 0xe5, 0xa6, 0x7c, 0xc8, 0x48, 0x7a, 0x2f, 0x1e, 0x9a, 0xab,
	0x2a, 0x9b, 0x1b, 0xf5, 0x7b, 0x9f, 0xce, 0x19, 0x9b, 0x87, 0x38, 0x43, 0x7a, 0xe9, 0xcc, 0x7c,
	0x9b, 0xb8, 0x71, 0x8c, 0x93, 0x22, 0xfe, 0xd1, 0xed, 0x38, 0x8e, 0x62, 0xb1, 0xc8, 0x83, 0x4f,
	0x6f, 0x07, 0x05, 0x89, 0x30, 0x17, 0x6e, 0x14, 0xe7, 0x80, 0x67, 0xf7, 0x0f, 0x81, 0xe3, 0xe4,
	0x4f, 0xe2, 0xe3, 0x1c, 0xf8, 0xed, 0x43, 0x3b, 0x28, 0x08, 0x53, 0x8e, 0x13, 0xf5, 0x93, 0x13,
	0x1c, 0xde, 0x5f, 0x29, 0x4a, 0x43, 0x41, 0x9c, 0x19, 0x09, 0xf3, 0x62, 0x83, 0xbf, 0xab, 0xd0,
	0x9c, 0x62, 0x2e, 0xa6, 0x72, 0x0e, 0xc8, 0x80, 0x8e, 0x1b, 0x13, 0x87, 0xd1, 0x70, 0xe1, 0x70,
	0x91, 0x10, 0x3a, 0xd7, 0xb5, 0xbe, 0x36, 0x6c, 0x9e, 0xd6, 0x56, 0xcb, 0x6e, 0x69, 0x4f, 0xb3,
	0xdb, 0x6e, 0x4c, 0x26, 0x34, 0x5c, 0x5c, 0xaa, 0x20, 0xd2, 0xa1, 0x4e, 0xd3, 0xc8, 0xc3, 0x09,
	0xd7, 0x4b, 0xfd, 0xf2, 0xb0, 0x6a, 0x17, 0x8f, 0xe8, 0x0c, 0x3a, 0x99, 0x38, 0x6e, 0x58, 0x30,
	0x95, 0xfb, 0xda, 0xb0, 0x75, 0xf4, 0xb1, 0x91, 0x0d, 0xca, 0x28, 0x06, 0x65, 0x64, 0x5c, 0x3f,
	0xbb, 0x61, 0x8a, 0xed, 0xdd, 0x22, 0x29, 0x2f, 0x30, 0x82, 0x96, 0x87, 0x7d, 0x16, 0x61, 0xee,
	0x10, 0x2a, 0xf4, 0x4a, 0x5f, 0x1b, 0xee, 0x1e, 0x75, 0x8d, 0xbc, 0x41, 0x63, 0x7d, 0x72, 0x83,
	0x0b, 0x57, 0xa4, 0xdc, 0x86, 0x1c, 0x6d, 0x51, 0x81, 0xbe, 0x86, 0x16, 0x65, 0xe2, 0x9a, 0xd0,
	0x39, 0xc5, 0x9c, 0xeb, 0x55, 0x55, 0xfe, 0xc9, 0x56, 0xf9, 0x33, 0x29, 0xa2, 0xbd, 0x09, 0x45,
	0x9f, 0x41, 0x25, 0x4d, 0x49, 0xa0, 0xd7, 0x54, 0xca, 0x9e, 0xa1, 0xec, 0x95, 0x39, 0xe5, 0xea,
	0xca, 0x1a, 0xdb, 0x2a, 0x8a, 0x5e, 0x00, 0xf8, 0x09, 0x76, 0x05, 0x0e, 0x1c, 0x57, 0xe8, 0x75,
	0x85, 0xed, 0x6d, 0xd1, 0x4f, 0x0b, 0x1b, 0xd8, 0xcd, 0x1c, 0x7d, 0x22, 0xd0, 0x01, 0x74, 0x24,
	0x9d, 0xf3, 0x96, 0x88, 0x6b, 0x87, 0x04, 0x0e, 0x09, 0xf4, 0x46, 0x5f, 0x1b, 0xb6, 0xed, 0x1d,
	0xf9, 0xfa, 0x35, 0x11, 0xd7, 0x56, 0x60, 0x05, 0xe8, 0x2b, 0x80, 0x37, 0x9c, 0x51, 0x67, 0x46,
	0x70, 0x18, 0xe8, 0x4d, 0x55, 0xe1, 0xf1, 0xe6, 0x69, 0x5e, 0x5d, 0x4e, 0xce, 0xb3, 0xc1, 0x35,
	0x25, 0xf0, 0xa5, 0xc4, 0xa1, 0x11, 0xb4, 0x69, 0x1a, 0x86, 0xae, 0x17, 0x62, 0x47, 0xb5, 0x01,
	0xdb, 0x89, 0xb2, 0x8d, 0x2c, 0x71, 0xa7, 0xc0, 0x5e, 0xa5, 0x24, 0x18, 0x0c, 0xa1, 0x96, 0x4d,
	0x12, 0xb5, 0xa0, 0x7e, 0x75, 0xfe, 0xc3, 0xf9, 0xe4, 0xf5, 0xf9, 0xde, 0x23, 0xd4, 0x80, 0xca,
	0xf7, 0x93, 0xc9, 0x78, 0x4f, 0x43, 0x75, 0x28, 0x9f, 0x9e, 0x8c, 0xf7, 0x4a, 0xa3, 0xd9, 0x6a,
	0xd9, 0xf5, 0x1a, 0x1a, 0x7a, 0x06, 0xad, 0x4c, 0xab, 0x93, 0x24, 0x71, 0x17, 0xa8, 0xea, 0xca,
	0xbf, 0xc1, 0xfe, 0x86, 0x87, 0x43, 0xe2, 0x99, 0xf1, 0x1f, 0x68, 0xf8, 0x5f, 0x60, 0x4d, 0x01,
	0x8f, 0xee, 0x40, 0xf6, 0x5a, 0x3c, 0x62, 0xc9, 0xdc, 0xe5, 0x1e, 0x4b, 0x82, 0xc1, 0x3f, 0x65,
	0x80, 0x69, 0x31, 0x94, 0x31, 0xda, 0x85, 0x12, 0x09, 0x94, 0x29, 0xdb, 0x76, 0x89, 0x04, 0xe8,
	0x29, 0x94, 0x48, 0xac, 0x97, 0x94, 0x49, 0x3b, 0xab, 0x65, 0xb7, 0x05, 0x4d, 0xa8, 0x93, 0xd8,
	0x71, 0x83, 0x20, 0xb1, 0x4b, 0x24, 0x46, 0x87, 0x50, 0x53, 0xc2, 0x72, 0xbd, 0xdc, 0x2f, 0x0f,
	0x5b, 0x47, 0x68, 0xdb, 0x3c, 0x76, 0x8e, 0x40, 0x23, 0xe8, 0xb8, 0x0e, 0xc5, 0x5c, 0x4a, 0xca,
	0xbc, 0x37, 0xd8, 0xcf, 0x1c, 0x77, 0x77, 0x52, 0xdb, 0x3d, 0x57, 0xc8, 0x89, 0x02, 0x22, 0x13,
	0xaa, 0x31, 0x93, 0x1e, 0xcd, 0x7c, 0xb6, 0xbf, 0xce, 0xb0, 0xa8, 0xb8, 0x90, 0x81, 0x6c, 0x87,
	0x06, 0x8f, 0xec, 0x0c, 0x87, 0x3e, 0x87, 0x8a, 0xdc, 0xd9, 0xdc, 0x64, 0x60, 0xa8, 0x05, 0xbe,
	0xe2, 0x38, 0x59, 0x03, 0x55, 0x1c, 0x99, 0x50, 0x97, 0xcd, 0x48, 0x0b, 0xd7, 0xb7, 0x85, 0xb4,
	0x28, 0x16, 0x99, 0x90, 0x05, 0x0a, 0x8d, 0xe0, 0xb1, 0x5a, 0x73, 0xd7, 0xf7, 0x59, 0x4a, 0x85,
	0xba, 0x62, 0x1d, 0x12, 0x70, 0xbd, 0xd1, 0x2f, 0x0f, 0xdb, 0xeb, 0x55, 0xfe, 0x60, 0x13, 0x24,
	0x5b, 0xb2, 0x02, 0x3e, 0x9a, 0xae, 0x96, 0xdd, 0x8b, 0x86, 0x86, 0x3e, 0x84, 0x2a, 0xa1, 0xe2,
	0xf8, 0x08, 0x01, 0xc7, 0x7e, 0x82, 0x85, 0xdc, 0xbe, 0x5e, 0x29, 0xd6, 0xd0, 0x31, 0xec, 0xfc,
	0xf6, 0xfb, 0xe1, 0x2b, 0x46, 0xe8, 0x54, 0x9a, 0x06, 0x65, 0x2c, 0xce, 0x66, 0x2d, 0xde, 0xdb,
	0xfd, 0x6b, 0xe7, 0x9d, 0x64, 0xd6, 0x78, 0xf0, 0x13, 0x3c, 0xf9, 0xf1, 0x56, 0xb1, 0x2d, 0x39,
	0x2b, 0x4a, 0xce, 0x4f, 0x00, 0x38, 0x8b, 0x70, 0xee, 0x78, 0x25, 0xab, 0xdd, 0x94, 0x6f, 0x94,
	0xb5, 0x47, 0x8d, 0xd5, 0xb2, 0x5b, 0x69, 0x68, 0x7d, 0x6d, 0x30, 0x86, 0xee, 0x5d, 0x94, 0x2c,
	0x15, 0xd6, 0xf8, 0x16, 0x8b, 0x76, 0x3f, 0xcb, 0x17, 0xd0, 0x3a, 0xb9, 0xb0, 0xe4, 0x85, 0x26,
	0x09, 0x50, 0x0f, 0x1a, 0x3e, 0xa3, 0x02, 0x53, 0xc1, 0xf3, 0xac, 0xf5, 0xf3, 0x80, 0x42, 0xe7,
	0x22, 0x21, 0x91, 0x9b, 0x2c, 0xe4, 0xee, 0x28, 0xf8, 0xc1, 0xfa, 0xf0, 0xf7, 0x6e, 0x97, 0xec,
	0xe9, 0x4b, 0xa8, 0xfa, 0xd7, 0x24, 0x6f, 0x47, 0xde, 0x40, 0x85, 0x33, 0xce, 0x6e, 0x04, 0x4e,
	0xa8, 0x1b, 0x7e, 0x27, 0xa3, 0x76, 0x06, 0x1a, 0x29, 0x79, 0x1a, 0xda, 0xe0, 0x17, 0xd8, 0xcf,
	0xeb, 0x65, 0x5b, 0xa3, 0x2a, 0xbe, 0x1b, 0x57, 0xf3, 0x3d, 0xa8, 0x2f, 0xd7, 0xad, 0x58, 0xd4,
	0x0f, 0xd3, 0x00, 0x6f, 0x10, 0x69, 0x0f, 0x21, 0x42, 0xab, 0x65, 0x77, 0xb7, 0xa1, 0x21, 0x80,
	0x8a, 0x6c, 0x15, 0x95, 0x48, 0x70, 0xfa, 0xf2, 0xd7, 0xf1, 0xff, 0xfd, 0x6e, 0x6d, 0x7e, 0x9e,
	0xbe, 0xc9, 0x5f, 0x7a, 0x35, 0x85, 0x3e, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x89, 0xd9, 0x48,
	0x8f, 0x34, 0x08, 0x00, 0x00,
}
