// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/feature_demo/demo_types.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	example/feature_demo/demo_types.proto
	example/feature_demo/demo_service.proto

It has these top-level messages:
	TestTypes
	TypeWithID
	MultiaccountTypeWithID
	MultiaccountTypeWithoutID
	APIOnlyType
	IntPoint
	CreateIntPointRequest
	CreateIntPointResponse
	ReadIntPointRequest
	ReadIntPointResponse
	UpdateIntPointRequest
	UpdateIntPointResponse
	DeleteIntPointRequest
	DeleteIntPointResponse
	ListIntPointResponse
	Something
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"
import gorm_types "github.com/infobloxopen/protoc-gen-gorm/types"
import google_protobuf1 "github.com/golang/protobuf/ptypes/wrappers"
import google_protobuf2 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enums are mapped to the their underlying numeric value in the db.
// This is practical from an API perspective, but tougher for debugging.
// Strings with validation constraints can be used instead if desired
type TestTypesStatus int32

const (
	TestTypes_UNKNOWN TestTypesStatus = 0
	TestTypes_GOOD    TestTypesStatus = 1
	TestTypes_BAD     TestTypesStatus = 2
)

var TestTypesStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "GOOD",
	2: "BAD",
}
var TestTypesStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"GOOD":    1,
	"BAD":     2,
}

func (x TestTypesStatus) String() string {
	return proto.EnumName(TestTypesStatus_name, int32(x))
}
func (TestTypesStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// test_types is a message that includes a representative sample of the
// available types
type TestTypes struct {
	// the (gorm.field).drop option allows for setting a field to be API only
	ApiOnlyString string `protobuf:"bytes,1,opt,name=api_only_string,json=apiOnlyString" json:"api_only_string,omitempty"`
	// repeated raw types are currently unsupported, so this field will be dropped
	// at the ORM level
	Numbers []int32 `protobuf:"varint,2,rep,packed,name=numbers" json:"numbers,omitempty"`
	// a StringValue represents a Nullable string
	OptionalString *google_protobuf1.StringValue `protobuf:"bytes,3,opt,name=optional_string,json=optionalString" json:"optional_string,omitempty"`
	BecomesInt     TestTypesStatus               `protobuf:"varint,4,opt,name=becomes_int,json=becomesInt,enum=example.TestTypesStatus" json:"becomes_int,omitempty"`
	// The Empty type serves no purpose outside of rpc calls and is dropped
	// automatically from objects
	Nothingness *google_protobuf2.Empty `protobuf:"bytes,5,opt,name=nothingness" json:"nothingness,omitempty"`
	// The UUIDValue custom type should act like a string at the API level, but is
	// automatically converted to and from a uuid.UUID (github.com/satori/go.uuid)
	Uuid *gorm_types.UUIDValue `protobuf:"bytes,6,opt,name=uuid" json:"uuid,omitempty"`
	// Timestamps convert to golang's time.Time type, and created_at and
	// updated_at values are automatically filled by GORM
	CreatedAt *google_protobuf3.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// This represents a foreign key to the 'type_with_id' type for associations
	// This could be hidden from the API (or soon autogenerated).
	TypeWithIdId uint32 `protobuf:"varint,8,opt,name=type_with_id_id,json=typeWithIdId" json:"type_with_id_id,omitempty"`
	// This is an arbitrary JSON string that is marshalled and unmarshalled
	// specially in grpc-gateway as a JSON object
	JsonField *gorm_types.JSONValue `protobuf:"bytes,9,opt,name=json_field,json=jsonField" json:"json_field,omitempty"`
}

func (m *TestTypes) Reset()                    { *m = TestTypes{} }
func (m *TestTypes) String() string            { return proto.CompactTextString(m) }
func (*TestTypes) ProtoMessage()               {}
func (*TestTypes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestTypes) GetApiOnlyString() string {
	if m != nil {
		return m.ApiOnlyString
	}
	return ""
}

func (m *TestTypes) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *TestTypes) GetOptionalString() *google_protobuf1.StringValue {
	if m != nil {
		return m.OptionalString
	}
	return nil
}

func (m *TestTypes) GetBecomesInt() TestTypesStatus {
	if m != nil {
		return m.BecomesInt
	}
	return TestTypes_UNKNOWN
}

func (m *TestTypes) GetNothingness() *google_protobuf2.Empty {
	if m != nil {
		return m.Nothingness
	}
	return nil
}

func (m *TestTypes) GetUuid() *gorm_types.UUIDValue {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *TestTypes) GetCreatedAt() *google_protobuf3.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TestTypes) GetTypeWithIdId() uint32 {
	if m != nil {
		return m.TypeWithIdId
	}
	return 0
}

func (m *TestTypes) GetJsonField() *gorm_types.JSONValue {
	if m != nil {
		return m.JsonField
	}
	return nil
}

// TypeWithID demonstrates some basic assocation behavior
type TypeWithID struct {
	// any field named 'id' is assumed by gorm to be the primary key for the
	// object.
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The field option also allows arbitrary tag setting, such as informing
	// gorm of a primary key, different column names or different types in the db
	Ip string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// A default has-many relationship, will error on generation if no FK field,
	// convention {typename}_id, is present. These FK fields will be automatically
	// populated on create and update.
	Things []*TestTypes `protobuf:"bytes,3,rep,name=things" json:"things,omitempty"`
	// A default has-one relationship, will error as above
	ANestedObject *TestTypes `protobuf:"bytes,4,opt,name=a_nested_object,json=aNestedObject" json:"a_nested_object,omitempty"`
}

func (m *TypeWithID) Reset()                    { *m = TypeWithID{} }
func (m *TypeWithID) String() string            { return proto.CompactTextString(m) }
func (*TypeWithID) ProtoMessage()               {}
func (*TypeWithID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TypeWithID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TypeWithID) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TypeWithID) GetThings() []*TestTypes {
	if m != nil {
		return m.Things
	}
	return nil
}

func (m *TypeWithID) GetANestedObject() *TestTypes {
	if m != nil {
		return m.ANestedObject
	}
	return nil
}

// MultiaccountTypeWithID demonstrates the generated multi-account support
type MultiaccountTypeWithID struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SomeField string `protobuf:"bytes,2,opt,name=some_field,json=someField" json:"some_field,omitempty"`
}

func (m *MultiaccountTypeWithID) Reset()                    { *m = MultiaccountTypeWithID{} }
func (m *MultiaccountTypeWithID) String() string            { return proto.CompactTextString(m) }
func (*MultiaccountTypeWithID) ProtoMessage()               {}
func (*MultiaccountTypeWithID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MultiaccountTypeWithID) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MultiaccountTypeWithID) GetSomeField() string {
	if m != nil {
		return m.SomeField
	}
	return ""
}

type MultiaccountTypeWithoutID struct {
	SomeField string `protobuf:"bytes,1,opt,name=some_field,json=someField" json:"some_field,omitempty"`
}

func (m *MultiaccountTypeWithoutID) Reset()                    { *m = MultiaccountTypeWithoutID{} }
func (m *MultiaccountTypeWithoutID) String() string            { return proto.CompactTextString(m) }
func (*MultiaccountTypeWithoutID) ProtoMessage()               {}
func (*MultiaccountTypeWithoutID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MultiaccountTypeWithoutID) GetSomeField() string {
	if m != nil {
		return m.SomeField
	}
	return ""
}

type APIOnlyType struct {
	// here the ormable flag is not used, so nothing will be generated for this
	// object at the ORM level, and when this type is used as a field or
	// repeated field in another message that field will be dropped in the Orm
	// model, and would have to be set by hook
	Contents string `protobuf:"bytes,1,opt,name=contents" json:"contents,omitempty"`
}

func (m *APIOnlyType) Reset()                    { *m = APIOnlyType{} }
func (m *APIOnlyType) String() string            { return proto.CompactTextString(m) }
func (*APIOnlyType) ProtoMessage()               {}
func (*APIOnlyType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *APIOnlyType) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func init() {
	proto.RegisterType((*TestTypes)(nil), "example.TestTypes")
	proto.RegisterType((*TypeWithID)(nil), "example.TypeWithID")
	proto.RegisterType((*MultiaccountTypeWithID)(nil), "example.MultiaccountTypeWithID")
	proto.RegisterType((*MultiaccountTypeWithoutID)(nil), "example.MultiaccountTypeWithoutID")
	proto.RegisterType((*APIOnlyType)(nil), "example.APIOnlyType")
	proto.RegisterEnum("example.TestTypesStatus", TestTypesStatus_name, TestTypesStatus_value)
}

func init() { proto.RegisterFile("example/feature_demo/demo_types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6a, 0xc3, 0x36,
	0x14, 0xc6, 0x67, 0x27, 0xcd, 0x9f, 0xe3, 0xa5, 0x09, 0x1a, 0xeb, 0x9c, 0x74, 0x5b, 0x43, 0xa0,
	0x90, 0x0e, 0x6a, 0x43, 0xba, 0x8b, 0x35, 0xbb, 0x6a, 0x49, 0x3b, 0xb2, 0xb1, 0x64, 0x73, 0xd3,
	0x15, 0x76, 0x63, 0x64, 0x5b, 0x71, 0x54, 0x6c, 0xc9, 0x58, 0x32, 0x6d, 0xde, 0x63, 0x2f, 0x93,
	0x3c, 0xc0, 0x9e, 0x6b, 0x58, 0x76, 0x4a, 0x69, 0x32, 0xe8, 0x8d, 0x41, 0x3a, 0xbf, 0xf3, 0x9d,
	0xa3, 0xef, 0xc8, 0x82, 0x73, 0xf2, 0x8a, 0xe3, 0x24, 0x22, 0xf6, 0x92, 0x60, 0x99, 0xa5, 0xc4,
	0x0d, 0x48, 0xcc, 0xed, 0xfc, 0xe3, 0xca, 0x75, 0x42, 0x84, 0x95, 0xa4, 0x5c, 0x72, 0x54, 0x2f,
	0xb1, 0xde, 0x38, 0xa4, 0x72, 0x95, 0x79, 0x96, 0xcf, 0x63, 0x9b, 0xb2, 0x25, 0xf7, 0x22, 0xfe,
	0xca, 0x13, 0xc2, 0x6c, 0xc5, 0xf9, 0x97, 0x21, 0x61, 0x97, 0x21, 0x4f, 0x63, 0x9b, 0x27, 0x92,
	0x72, 0x26, 0xec, 0x7c, 0x51, 0x88, 0xf4, 0xae, 0x3f, 0x9b, 0xab, 0x2a, 0xdb, 0xef, 0xea, 0xf7,
	0xbe, 0x0f, 0x39, 0x0f, 0x23, 0x52, 0x90, 0x5e, 0xb6, 0xb4, 0x5f, 0x52, 0x9c, 0x24, 0x24, 0xdd,
	0xc5, 0x4f, 0x3f, 0xc6, 0x49, 0x9c, 0xc8, 0x75, 0x19, 0x3c, 0xfb, 0x18, 0x94, 0x34, 0x26, 0x42,
	0xe2, 0x38, 0x29, 0x80, 0xc1, 0x3f, 0x55, 0x68, 0x2e, 0x88, 0x90, 0x8b, 0xbc, 0x22, 0xb2, 0xa0,
	0x8d, 0x13, 0xea, 0x72, 0x16, 0xad, 0x5d, 0x21, 0x53, 0xca, 0x42, 0x53, 0xeb, 0x6b, 0xc3, 0xe6,
	0x6d, 0x6d, 0xbb, 0xe9, 0xea, 0x1d, 0xcd, 0x69, 0xe1, 0x84, 0xce, 0x59, 0xb4, 0x7e, 0x50, 0x41,
	0x64, 0x42, 0x9d, 0x65, 0xb1, 0x47, 0x52, 0x61, 0xea, 0xfd, 0xca, 0xf0, 0xc8, 0xd9, 0x2d, 0xd1,
	0x1d, 0xb4, 0x0b, 0x1b, 0x70, 0xb4, 0x53, 0xaa, 0xf4, 0xb5, 0xa1, 0x31, 0xfa, 0xd6, 0x2a, 0x5a,
	0xb2, 0x76, 0x2d, 0x59, 0x85, 0xd6, 0x5f, 0x38, 0xca, 0x88, 0x73, 0xbc, 0x4b, 0x2a, 0x0b, 0x8c,
	0xc1, 0xf0, 0x88, 0xcf, 0x63, 0x22, 0x5c, 0xca, 0xa4, 0x59, 0xed, 0x6b, 0xc3, 0xe3, 0x51, 0xd7,
	0x2a, 0x47, 0x62, 0xbd, 0x75, 0x6e, 0x09, 0x89, 0x65, 0x26, 0x1c, 0x28, 0xe9, 0x29, 0x93, 0xe8,
	0x27, 0x30, 0x18, 0x97, 0x2b, 0xca, 0x42, 0x46, 0x84, 0x30, 0x8f, 0x54, 0xf9, 0x93, 0xbd, 0xf2,
	0x77, 0xb9, 0x5d, 0xce, 0x7b, 0x14, 0x5d, 0x40, 0x35, 0xcb, 0x68, 0x60, 0xd6, 0x54, 0xca, 0xd7,
	0x96, 0x1a, 0x64, 0x31, 0x93, 0xc7, 0xc7, 0xe9, 0xa4, 0x68, 0x55, 0x21, 0xe8, 0x1a, 0xc0, 0x4f,
	0x09, 0x96, 0x24, 0x70, 0xb1, 0x34, 0xeb, 0x2a, 0xa1, 0xb7, 0x57, 0x63, 0xb1, 0x73, 0xdd, 0x69,
	0x96, 0xf4, 0x8d, 0x44, 0xe7, 0xd0, 0xce, 0x35, 0xdd, 0x17, 0x2a, 0x57, 0x2e, 0x0d, 0x5c, 0x1a,
	0x98, 0x8d, 0xbe, 0x36, 0x6c, 0x39, 0x5f, 0xe6, 0xdb, 0x4f, 0x54, 0xae, 0xa6, 0xc1, 0x34, 0x40,
	0x3f, 0x02, 0x3c, 0x0b, 0xce, 0xdc, 0x25, 0x25, 0x51, 0x60, 0x36, 0xf7, 0x5b, 0xfa, 0xf5, 0x61,
	0x3e, 0x2b, 0x5a, 0x6a, 0xe6, 0xe0, 0x7d, 0xce, 0x0d, 0x86, 0x50, 0x2b, 0x2c, 0x41, 0x06, 0xd4,
	0x1f, 0x67, 0xbf, 0xcd, 0xe6, 0x4f, 0xb3, 0xce, 0x17, 0xa8, 0x01, 0xd5, 0x5f, 0xe6, 0xf3, 0x49,
	0x47, 0x43, 0x75, 0xa8, 0xdc, 0xde, 0x4c, 0x3a, 0xfa, 0xf8, 0xab, 0xed, 0xa6, 0xdb, 0x6e, 0x68,
	0x3d, 0x43, 0xc4, 0x3c, 0x0d, 0xb1, 0xf0, 0x78, 0x1a, 0x0c, 0xfe, 0xd5, 0x00, 0x16, 0xbb, 0x2e,
	0x26, 0xe8, 0x18, 0x74, 0x1a, 0xa8, 0xab, 0xd0, 0x72, 0x74, 0x1a, 0xa0, 0x33, 0xd0, 0x69, 0x62,
	0xea, 0xea, 0x6a, 0xb4, 0xb7, 0x9b, 0xae, 0x01, 0x4d, 0xa8, 0xd3, 0xc4, 0xc5, 0x41, 0x90, 0x3a,
	0x3a, 0x4d, 0xd0, 0x0f, 0x50, 0x53, 0x76, 0x0a, 0xb3, 0xd2, 0xaf, 0x0c, 0x8d, 0x11, 0xda, 0x1f,
	0x99, 0x53, 0x12, 0x68, 0x0c, 0x6d, 0xec, 0x32, 0x22, 0x72, 0x0f, 0xb9, 0xf7, 0x4c, 0xfc, 0x62,
	0xce, 0x87, 0x93, 0x5a, 0x78, 0xa6, 0xc8, 0xb9, 0x02, 0xc7, 0x67, 0xdb, 0x4d, 0xf7, 0xb4, 0xa1,
	0xa1, 0x6f, 0xe0, 0x88, 0x32, 0x79, 0x35, 0x42, 0x20, 0x88, 0x9f, 0x12, 0x99, 0xdf, 0x96, 0x9e,
	0x9e, 0x68, 0x83, 0x3f, 0xe1, 0xe4, 0xf7, 0x2c, 0x92, 0x14, 0xfb, 0x3e, 0xcf, 0x98, 0x3c, 0x78,
	0xa6, 0xaa, 0x3a, 0xd3, 0x77, 0x00, 0x82, 0xc7, 0xa4, 0xf4, 0x59, 0x9d, 0xcd, 0x69, 0xe6, 0x3b,
	0xca, 0xd0, 0x71, 0x63, 0xbb, 0xe9, 0x56, 0x1b, 0x5a, 0x5f, 0x1b, 0x4c, 0xa0, 0x7b, 0x48, 0x92,
	0x67, 0x72, 0x3a, 0xf9, 0xa0, 0xa2, 0xfd, 0xbf, 0xca, 0x05, 0x18, 0x37, 0x7f, 0x4c, 0xf3, 0x7f,
	0x29, 0x17, 0x40, 0x3d, 0x68, 0xf8, 0x9c, 0x49, 0xc2, 0xa4, 0x28, 0xb3, 0xde, 0xd6, 0xb7, 0xf7,
	0x7f, 0x4f, 0x3e, 0xfb, 0x7c, 0x1c, 0x7a, 0xd2, 0x7e, 0x2e, 0x37, 0xbd, 0x9a, 0xa2, 0xaf, 0xfe,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x21, 0x11, 0x9a, 0x20, 0xf9, 0x04, 0x00, 0x00,
}
