// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/feature_demo/test2.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	example/feature_demo/test2.proto
	example/feature_demo/test.proto

It has these top-level messages:
	IntPoint
	CreateIntPointRequest
	CreateIntPointResponse
	ReadIntPointRequest
	ReadIntPointResponse
	UpdateIntPointRequest
	UpdateIntPointResponse
	DeleteIntPointRequest
	ListIntPointResponse
	TestTypes
	TypeWithId
	MultitenantTypeWithId
	MultitenantTypeWithoutId
	ApiOnlyType
	TypeBecomesEmpty
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntPoint struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	X  int32  `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	Y  int32  `protobuf:"varint,3,opt,name=y" json:"y,omitempty"`
}

func (m *IntPoint) Reset()                    { *m = IntPoint{} }
func (m *IntPoint) String() string            { return proto.CompactTextString(m) }
func (*IntPoint) ProtoMessage()               {}
func (*IntPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IntPoint) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IntPoint) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *IntPoint) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type CreateIntPointRequest struct {
	Payload *IntPoint `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateIntPointRequest) Reset()                    { *m = CreateIntPointRequest{} }
func (m *CreateIntPointRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIntPointRequest) ProtoMessage()               {}
func (*CreateIntPointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateIntPointRequest) GetPayload() *IntPoint {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateIntPointResponse struct {
	Result *IntPoint `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreateIntPointResponse) Reset()                    { *m = CreateIntPointResponse{} }
func (m *CreateIntPointResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateIntPointResponse) ProtoMessage()               {}
func (*CreateIntPointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateIntPointResponse) GetResult() *IntPoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadIntPointRequest struct {
	Payload *IntPoint `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *ReadIntPointRequest) Reset()                    { *m = ReadIntPointRequest{} }
func (m *ReadIntPointRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadIntPointRequest) ProtoMessage()               {}
func (*ReadIntPointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadIntPointRequest) GetPayload() *IntPoint {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ReadIntPointResponse struct {
	Result *IntPoint `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadIntPointResponse) Reset()                    { *m = ReadIntPointResponse{} }
func (m *ReadIntPointResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadIntPointResponse) ProtoMessage()               {}
func (*ReadIntPointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadIntPointResponse) GetResult() *IntPoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateIntPointRequest struct {
	Payload *IntPoint `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateIntPointRequest) Reset()                    { *m = UpdateIntPointRequest{} }
func (m *UpdateIntPointRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateIntPointRequest) ProtoMessage()               {}
func (*UpdateIntPointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateIntPointRequest) GetPayload() *IntPoint {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateIntPointResponse struct {
	Result *IntPoint `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UpdateIntPointResponse) Reset()                    { *m = UpdateIntPointResponse{} }
func (m *UpdateIntPointResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateIntPointResponse) ProtoMessage()               {}
func (*UpdateIntPointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateIntPointResponse) GetResult() *IntPoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteIntPointRequest struct {
	Payload *IntPoint `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *DeleteIntPointRequest) Reset()                    { *m = DeleteIntPointRequest{} }
func (m *DeleteIntPointRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIntPointRequest) ProtoMessage()               {}
func (*DeleteIntPointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteIntPointRequest) GetPayload() *IntPoint {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListIntPointResponse struct {
	Results []*IntPoint `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListIntPointResponse) Reset()                    { *m = ListIntPointResponse{} }
func (m *ListIntPointResponse) String() string            { return proto.CompactTextString(m) }
func (*ListIntPointResponse) ProtoMessage()               {}
func (*ListIntPointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListIntPointResponse) GetResults() []*IntPoint {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*IntPoint)(nil), "example.int_point")
	proto.RegisterType((*CreateIntPointRequest)(nil), "example.CreateIntPointRequest")
	proto.RegisterType((*CreateIntPointResponse)(nil), "example.CreateIntPointResponse")
	proto.RegisterType((*ReadIntPointRequest)(nil), "example.ReadIntPointRequest")
	proto.RegisterType((*ReadIntPointResponse)(nil), "example.ReadIntPointResponse")
	proto.RegisterType((*UpdateIntPointRequest)(nil), "example.UpdateIntPointRequest")
	proto.RegisterType((*UpdateIntPointResponse)(nil), "example.UpdateIntPointResponse")
	proto.RegisterType((*DeleteIntPointRequest)(nil), "example.DeleteIntPointRequest")
	proto.RegisterType((*ListIntPointResponse)(nil), "example.ListIntPointResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Point service

type PointClient interface {
	CreateIntPoint(ctx context.Context, in *CreateIntPointRequest, opts ...grpc.CallOption) (*CreateIntPointResponse, error)
	ReadIntPoint(ctx context.Context, in *ReadIntPointRequest, opts ...grpc.CallOption) (*ReadIntPointResponse, error)
	UpdateIntPoint(ctx context.Context, in *UpdateIntPointRequest, opts ...grpc.CallOption) (*UpdateIntPointResponse, error)
	ListIntPoint(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ListIntPointResponse, error)
	DeleteIntPoint(ctx context.Context, in *DeleteIntPointRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	CustomMethod(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type pointClient struct {
	cc *grpc.ClientConn
}

func NewPointClient(cc *grpc.ClientConn) PointClient {
	return &pointClient{cc}
}

func (c *pointClient) CreateIntPoint(ctx context.Context, in *CreateIntPointRequest, opts ...grpc.CallOption) (*CreateIntPointResponse, error) {
	out := new(CreateIntPointResponse)
	err := grpc.Invoke(ctx, "/example.Point/CreateIntPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) ReadIntPoint(ctx context.Context, in *ReadIntPointRequest, opts ...grpc.CallOption) (*ReadIntPointResponse, error) {
	out := new(ReadIntPointResponse)
	err := grpc.Invoke(ctx, "/example.Point/ReadIntPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) UpdateIntPoint(ctx context.Context, in *UpdateIntPointRequest, opts ...grpc.CallOption) (*UpdateIntPointResponse, error) {
	out := new(UpdateIntPointResponse)
	err := grpc.Invoke(ctx, "/example.Point/UpdateIntPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) ListIntPoint(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ListIntPointResponse, error) {
	out := new(ListIntPointResponse)
	err := grpc.Invoke(ctx, "/example.Point/ListIntPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) DeleteIntPoint(ctx context.Context, in *DeleteIntPointRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/example.Point/DeleteIntPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) CustomMethod(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/example.Point/CustomMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Point service

type PointServer interface {
	CreateIntPoint(context.Context, *CreateIntPointRequest) (*CreateIntPointResponse, error)
	ReadIntPoint(context.Context, *ReadIntPointRequest) (*ReadIntPointResponse, error)
	UpdateIntPoint(context.Context, *UpdateIntPointRequest) (*UpdateIntPointResponse, error)
	ListIntPoint(context.Context, *google_protobuf.Empty) (*ListIntPointResponse, error)
	DeleteIntPoint(context.Context, *DeleteIntPointRequest) (*google_protobuf.Empty, error)
	CustomMethod(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
}

func RegisterPointServer(s *grpc.Server, srv PointServer) {
	s.RegisterService(&_Point_serviceDesc, srv)
}

func _Point_CreateIntPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIntPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).CreateIntPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Point/CreateIntPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).CreateIntPoint(ctx, req.(*CreateIntPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_ReadIntPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadIntPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).ReadIntPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Point/ReadIntPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).ReadIntPoint(ctx, req.(*ReadIntPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_UpdateIntPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIntPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).UpdateIntPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Point/UpdateIntPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).UpdateIntPoint(ctx, req.(*UpdateIntPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_ListIntPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).ListIntPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Point/ListIntPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).ListIntPoint(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_DeleteIntPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIntPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).DeleteIntPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Point/DeleteIntPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).DeleteIntPoint(ctx, req.(*DeleteIntPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_CustomMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).CustomMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Point/CustomMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).CustomMethod(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Point_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.Point",
	HandlerType: (*PointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIntPoint",
			Handler:    _Point_CreateIntPoint_Handler,
		},
		{
			MethodName: "ReadIntPoint",
			Handler:    _Point_ReadIntPoint_Handler,
		},
		{
			MethodName: "UpdateIntPoint",
			Handler:    _Point_UpdateIntPoint_Handler,
		},
		{
			MethodName: "ListIntPoint",
			Handler:    _Point_ListIntPoint_Handler,
		},
		{
			MethodName: "DeleteIntPoint",
			Handler:    _Point_DeleteIntPoint_Handler,
		},
		{
			MethodName: "CustomMethod",
			Handler:    _Point_CustomMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/feature_demo/test2.proto",
}

func init() { proto.RegisterFile("example/feature_demo/test2.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x13, 0x35, 0x81, 0x21, 0xe4, 0xb0, 0xb4, 0x55, 0x30, 0x5f, 0x91, 0x4f, 0x15, 0x6a,
	0x6d, 0x29, 0xdc, 0xca, 0x01, 0xd4, 0x24, 0x20, 0x10, 0x95, 0x90, 0x2b, 0x2e, 0x5c, 0x2a, 0xa7,
	0x9e, 0xb8, 0x96, 0xec, 0x9d, 0xc5, 0x3b, 0x96, 0x92, 0x9f, 0x06, 0x7f, 0x86, 0xbf, 0x82, 0x92,
	0x75, 0x23, 0xbb, 0xd8, 0x08, 0x35, 0x3d, 0xce, 0xee, 0x9b, 0x37, 0x6f, 0xe7, 0xed, 0x0c, 0x8c,
	0x70, 0x19, 0xa4, 0x2a, 0x41, 0x6f, 0x81, 0x01, 0xe7, 0x19, 0x5e, 0x86, 0x98, 0x92, 0xc7, 0xa8,
	0x79, 0xec, 0xaa, 0x8c, 0x98, 0x44, 0xaf, 0x40, 0xd8, 0xcf, 0x22, 0xa2, 0x28, 0x41, 0x6f, 0x73,
	0x3c, 0xcf, 0x17, 0x1e, 0xa6, 0x8a, 0x57, 0x06, 0x65, 0x9f, 0x46, 0x31, 0x5f, 0xe7, 0x73, 0xf7,
	0x8a, 0x52, 0x2f, 0x96, 0x0b, 0x9a, 0x27, 0xb4, 0x24, 0x85, 0xd2, 0xa0, 0xaf, 0x4e, 0x22, 0x94,
	0x27, 0x11, 0x65, 0xa9, 0x47, 0x8a, 0x63, 0x92, 0xda, 0x5b, 0x07, 0x26, 0xd7, 0x79, 0x07, 0x0f,
	0x63, 0xc9, 0x97, 0x8a, 0x62, 0xc9, 0x62, 0x00, 0xed, 0x38, 0x1c, 0x5a, 0x23, 0xeb, 0xe8, 0xb1,
	0xdf, 0x8e, 0x43, 0xd1, 0x07, 0x6b, 0x39, 0x6c, 0x8f, 0xac, 0xa3, 0x3d, 0xdf, 0x5a, 0xae, 0xa3,
	0xd5, 0xb0, 0x63, 0xa2, 0xd5, 0x69, 0xf7, 0xd7, 0xcf, 0xa7, 0xed, 0x07, 0x96, 0x33, 0x83, 0x83,
	0x49, 0x86, 0x01, 0xe3, 0x27, 0xc9, 0x5f, 0xd7, 0x2c, 0x3e, 0xfe, 0xc8, 0x51, 0xb3, 0x38, 0x86,
	0x9e, 0x0a, 0x56, 0x09, 0x05, 0x86, 0xf1, 0xd1, 0x58, 0xb8, 0xc5, 0x6b, 0xdc, 0x6d, 0x45, 0xff,
	0x06, 0xe2, 0x4c, 0xe1, 0xf0, 0x36, 0x8d, 0x56, 0x24, 0x35, 0x8a, 0xd7, 0xd0, 0xcd, 0x50, 0xe7,
	0x09, 0xff, 0x83, 0xa6, 0x40, 0x38, 0x13, 0x78, 0xe2, 0x63, 0x10, 0xee, 0x26, 0xe5, 0x0c, 0xf6,
	0xab, 0x24, 0x77, 0x10, 0x32, 0x83, 0x83, 0x6f, 0x2a, 0xbc, 0x8f, 0xae, 0xdc, 0xa6, 0xb9, 0x9b,
	0x98, 0x29, 0x26, 0xb8, 0xbb, 0x98, 0xfd, 0x2f, 0xb1, 0xe6, 0xbf, 0xa4, 0x1c, 0x43, 0xcf, 0x14,
	0xd2, 0x43, 0x6b, 0xd4, 0x69, 0x62, 0x29, 0x20, 0xe3, 0xdf, 0x1d, 0xd8, 0xdb, 0xe4, 0x8b, 0x0b,
	0x18, 0x54, 0x2d, 0x17, 0x2f, 0xb7, 0x89, 0xb5, 0x5f, 0xca, 0x7e, 0xd5, 0x78, 0x6f, 0xa4, 0x38,
	0x2d, 0x71, 0x0e, 0xfd, 0xb2, 0x79, 0xe2, 0xf9, 0x36, 0xa5, 0xe6, 0x63, 0xd8, 0x2f, 0x1a, 0x6e,
	0xb7, 0x74, 0x17, 0x30, 0xa8, 0x1a, 0x50, 0xd2, 0x58, 0x6b, 0x70, 0x49, 0x63, 0xbd, 0x73, 0x4e,
	0x4b, 0x7c, 0x84, 0x7e, 0xb9, 0x91, 0xe2, 0xd0, 0x35, 0xd3, 0xed, 0xde, 0x4c, 0xb7, 0x3b, 0x5b,
	0x4f, 0x77, 0x49, 0x5d, 0x5d, 0xdf, 0x9d, 0x96, 0xf8, 0x0c, 0x83, 0xaa, 0xb1, 0x25, 0x75, 0xb5,
	0x8e, 0xdb, 0x0d, 0xa5, 0x9c, 0x96, 0x78, 0x0f, 0xfd, 0x49, 0xae, 0x99, 0xd2, 0x73, 0xe4, 0x6b,
	0x0a, 0x1b, 0x45, 0x35, 0x32, 0xd8, 0xc5, 0x46, 0x38, 0xfb, 0xf0, 0x7d, 0xfa, 0xbf, 0x0b, 0xa9,
	0x6e, 0x01, 0xbe, 0x2d, 0x0e, 0xe7, 0xdd, 0x0d, 0xfa, 0xcd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xea, 0xe2, 0xa4, 0xb0, 0x27, 0x05, 0x00, 0x00,
}
